language: python
python: 3.5

os:
    - linux

install:
    - pip3 install pep8

script:
    - cd smoketest && ./do_test.sh < testcases.tsv
    - pep8 ./shelldoc

notifications:
    email:
        on_success: never
        on_failure: always
