language: python
python: 3.5

os:
    - linux

install:
    - pip3 install pycodestyle

script:
    - cd smoketest && ./do_test.sh < testcases.tsv
    - pycodestyle ./shelldoc

notifications:
    email:
        on_success: never
        on_failure: always
